### ISSUE TITLE
Displays configurations that are not mine

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#361] opened 2024-01-31 14:02 UTC
When on the order page I click on the list of configs, the imager displays configurations that are not mine (hopefully from folks from the same silo, but not even sure). I'd suggest displaying only configs from the current user (we initially thought that people from the same org would share configs, but that's not happening).

![Capture d’écran 2024-01-31 à 14 58 14](https://github.com/offspot/cardshop/assets/21675885/b7a81e63-4a6c-44cd-936c-510c61c872a4)

**Comment by rgaudin** [comment] 2024-01-31 14:55
Closing as duplicate of #150. Please use the `bug` label if you know what you're doing as it raises immediate investigation.

**Closed by rgaudin** 2024-01-31 14:55 UTC
Labels: bug
