### ISSUE TITLE
Handle retired ZIM

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#287] opened 2022-01-24 12:56 UTC
[L832R61EE](https://cardshop.hotspot.kiwix.org/orders/L832R61EE) failed with `Incorrect values for `zim_install`: Science_in_the_bath_freshest-produce.en aimhi_geography.en`

Looking at the configuration, I see that `Science in the bath` was selected twice, and indeed the configuration dashboard has it twice:
![Capture d’écran 2022-01-24 à 13 55 27](https://user-images.githubusercontent.com/21675885/150786644-ec82f577-a414-4735-94cb-7a0006c9fdec.png)
but also 
![Capture d’écran 2022-01-24 à 13 47 01](https://user-images.githubusercontent.com/21675885/150785553-b5e9b217-2cd4-40b2-9f27-63c9f933c95b.png)
Hovering on the later I can see two files that have _almost_ the same name except that one is `scienceinthebath_en_freshest-produce.en` and the other `Science_in_the_bath_freshest-produce.en` (so just one uppercase difference).
So clearly the library has three files too many on offer.

I looked up download.kiwix.org and could only find one instance however: https://download.kiwix.org/zim/videos/scienceinthebath_en_freshest-produce_2022-01.zim

FWIW the recipe is here: https://farm.openzim.org/recipes/scienceinthebath_playlist

**Comment by rgaudin** [comment] 2022-01-24 13:52
OK, there are two known issues here:

- catalog synchronization. The cardshop caches [the catalog](mirror.download.kiwix.org/library/ideascube.yml) for 24h. I believe in this case, the catalog has changed recently and we shall see a single occurence of _Science In The Bath_ tomorrow. This will be partly fixed by the move to OPDS (#131) although we'd still use some cache. I suggest to shrink the current cache to 3h now.
- ZIM obsolescence. As far as the Cardshop is concerned, those are just two different ZIMs because they have different names so it's not a _duplicate_. The problem is (error is at hotspot which downloads the catalog on launch) that the referenced ZIM is not in the catalog anymore (meaning that its file is not downloadable anymore). We've already discussed this but I couldn't find the issue (or we didn't create one?). We need to define a practical way to handle such case:
  - silently remove the unavailable ZIM from the order and pursue (might be the only ZIM or content though!)
  - fail the order with an error message indicating a selected ZIM has retire and configuration must be updated.
  - something else?
In addition, we need a system that checks for retired ZIM in configs and informs users about the issue. When? On config edit ? on Order placement ?

**Comment by kelson42** [comment] 2022-01-25 15:35
@rgaudin Independently of any other consideration, the cardshop recipe should be checked as early as possible against the library opds stream... to avoid later crash.

**Comment by rgaudin** [comment] 2022-01-25 15:39
Doesn't answer the question of the when except for the obvious “on order creation”. Just to be clear, the current check is at installer startup so first thing once the task is picked up by the worker. We'd want the cardshop to check that before scheduling the order… using OPDS, once we add OPDS support.

**Comment by kelson42** [comment] 2022-01-25 16:44
@rgaudin Yes, Cardshop should be able to test a recipe periodicaly and even before a cretor is started.

**Closed** 2022-06-08 14:05 UTC
Labels: bug

**Comment by rgaudin** [comment] 2022-06-08 14:15
<img width="1139" alt="Screen Shot 2022-06-08 at 16 14 59" src="https://user-images.githubusercontent.com/57929/172639275-af632e4a-b8c3-4f5a-8372-eace05c32135.png">

<img width="1141" alt="Screen Shot 2022-06-08 at 16 15 15" src="https://user-images.githubusercontent.com/57929/172639292-bfd39c28-5316-446f-a18d-83c82bbf6976.png">
