### ISSUE TITLE
Preloaded file resources should be directly uploadable, much like the branding

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#373] opened 2024-02-01 13:22 UTC
I am not sure why it is possible to upload an image but not a zip file. Not every user has a server available somewhere where they can drop a zip file, and I suspect than more often than not a dropbox or google drive link could fail.

**Comment by rgaudin** [comment] 2024-02-01 13:29
Duplicate of #106

**Closed by rgaudin** 2024-02-01 13:29 UTC
Labels: enhancement
