### ISSUE TITLE
Confirm order page should list config content, not config name/link

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#383] opened 2024-02-07 11:30 UTC
Currently the first line of the order summary is called `configuration` but only adds a link to the setup wizard. It would be much more user friendly to list:
- SSID
- wifi password only if there is one
- List of contents actually selected
- minimum SD card size (currently the actual image size is being shown but that has little actionable value)

**Comment by rgaudin** [comment] 2024-02-07 13:56
So you consider that informing the user about the size of the Image (and thus the size of the file s•he will have to download) has little value because not actionnable (it is! it allows to decide whether to pursue or not) **but** you want to list all content which wont be actionnable neither ; except by going back to the config edition via the link that was there the whole time.

My problem with this request is that we'll end-up listing everything from the page they just left (since the order button is right in the config editor).

Now that we don't select the config from a list, this makes little sense. If the issue is with the “Place order” button from orders page (auto-selecting last edited) ; maybe that button should be removed instead

**Comment by rgaudin** [comment] 2024-02-07 16:11
Fixed in 863ae9b ; we've agreed to only add Apps/Content/Learning tools list

**Closed by rgaudin** 2024-02-07 16:11 UTC
Labels: enhancement
