### ISSUE TITLE
Branding returns error eventhough file size is correct

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#358] opened 2024-01-15 16:22 UTC
I created a configuration, selected an image (151 kB) and then hit `Update config`. Then moved to the content tab, selected some content then updated again. I get an error message (`Your config has errors and can not be saved. Please fix them and retry.`) telling me that my branding image is too large (over 1.03MB).

I am still able to place an order but haven't checked yet if the image will be included.

**Comment by rgaudin** [comment] 2024-01-15 17:38
I cannot reproduce following those steps ; I suppose it's not exactly how it hapened.
Care to share the **source image**. Looking at it, it's probably a JPEG that we converted to PNG… and JPEG to PNG usually increases size so there might be something there.

**Comment by Popolechien** [comment] 2024-01-15 19:17
![_4f641df5-0c20-4281-9287-0d6d5a5a8ede](https://github.com/offspot/cardshop/assets/21675885/ac421618-c46e-4764-bc42-5e9767c85517)
I tried again with this jpeg image and another config, same result.

1. create config, input name, update
2. Go to branding, add image, update
3. Go to content, add content, update -> error

Except that now after step 2 I get `KeyError at /configurations/1012`

![image](https://github.com/offspot/cardshop/assets/21675885/a61ab8b8-3aea-496b-9b58-bd4931dad4c0)

**Comment by rgaudin** [comment] 2024-01-15 22:55
That error message is unrelated and was due to a new push that I've fixed. We can disregard that screenshot.

The issue is valid though and as I expected is due to JPEG to PNG conversion.

**Comment by rgaudin** [comment] 2024-01-16 13:05
Fixed in 082eff1

**Closed by rgaudin** 2024-01-16 13:05 UTC
Labels: bug
